#!/usr/bin/perl

# Copyright (c) 2012 Jason Hancock <jsnbyh@gmail.com>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is furnished
# to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.
#
# This file is part of the nagios-cpu bundle that can be found
# at https://github.com/jasonhancock/nagios-html-email

use strict;
use warnings;

use MIME::Lite;
use URI::Escape;
use Sys::Hostname;

use Getopt::Long;
my $nagios_url = '';
my %NAGIOS = ();

GetOptions (
	'nagioshost=s'	=> \$nagios_url,
	'param=s' 		=> \%NAGIOS
) || die('You must pass the url to your nagios installation as the first argument, and other params as key=value');

die('You must pass the url to your nagios installation as the first argument') if not $nagios_url;

my $color_red    = '#FF8080';
my $color_green  = '#80FF80';
my $color_yellow = '#FFFF80';
my $color_orange = '#FF9900';
my $color_even   = '#C9C9C9';
my $color_odd    = '#EAEAEA';

my %colors=(
    'PROBLEM'         => $color_red,
    'RECOVERY'        => $color_green,
    'ACKNOWLEDGEMENT' => $color_yellow,
    'CRITICAL'        => $color_red,
    'WARNING'         => $color_yellow,
    'OK'              => $color_green,
    'UNKNOWN'         => $color_orange,
    'UP'              => $color_green,
    'DOWN'            => $color_red,
    'UNREACHABLE'     => $color_orange,
);

my %allowed_types = (
    'PROBLEM'         => 1,
    'RECOVERY'        => 1,
    'ACKNOWLEDGEMENT' => 1
);
my @exceptions = (
	'CHECK_NRPE', 
	'check timed out', 
	'PLUGIN TIMEOUT', 
	'Socket timeout', 
	'stdout', 
	'stderr', 
	'out of bounds'
	);

exit if !defined($allowed_types{$NAGIOS{NOTIFICATIONTYPE}});
my $type = $NAGIOS{SERVICEATTEMPT} ? 'service' : 'host';

my @skip = ();
my $contact = $NAGIOS{CONTACTEMAIL};
if($type eq 'service') {
	@skip = grep { $NAGIOS{SERVICEOUTPUT} =~ /$_/; } @exceptions;
} else {
	@skip = grep { $NAGIOS{HOSTOUTPUT} =~ /$_/; } @exceptions;
}
if (scalar @skip) {
	if ($NAGIOS{ADMIN}) {
		$contact = $NAGIOS{ADMIN};
	}
	my @skip_mail = ();
	my @recipients = split(/,/, $NAGIOS{NOTIFICATIONRECIPIENTS});
	my $throwit = shift @recipients;
	@skip_mail = grep { $NAGIOS{CONTACTEMAIL} =~ /$_/; } @recipients;
	if  (scalar @skip_mail) {
		exit 0;
	}
}
# dark #c9c9c9c9;
# light #eaeaea;

my $font = 'helvetica, arial';
my $style_th_even = '"background-color: #eeeeee; font-weight: bold; width: 130px;"';
my $style_th_odd  = '"background-color: #f7f7f7; font-weight: bold; width: 130px;"';
my $style_td_even = '"background-color: #eeeeee;"';
my $style_td_odd  = '"background-color: #f7f7f7;"';
my $style_table   = "\"font-family: $font; font-size: 12px;\"";

my $style_state = sprintf('"background-color: %s"',
    $type eq 'service'
    ? $colors{$NAGIOS{SERVICESTATE}}
    : $colors{$NAGIOS{HOSTSTATE}}
);

my $subject = sprintf('Nagios %s Alert: %s',
    ucfirst($type),
    $type eq 'service' ? $NAGIOS{HOSTNAME} . '/' . $NAGIOS{SERVICEDESC} : $NAGIOS{HOSTNAME},
);

my $host_url = sprintf('%s/cgi-bin/status.cgi?navbarsearch=1&host=%s',
    $nagios_url,
    $NAGIOS{HOSTNAME}
);
my @rows;
my $notification_title;
my $summary;
my $ack_url;
my $output;

if($type eq 'service') {
    my $service_url = sprintf('%s/cgi-bin/extinfo.cgi?type=2&host=%s&service=%s',
        $nagios_url,
        $NAGIOS{HOSTNAME},
        uri_escape($NAGIOS{SERVICEDESC})
    );

    $notification_title = 'Nagios Service Notification';
	$ack_url = $service_url;
	$output = $NAGIOS{SERVICEOUTPUT};
	$summary = "<a href=\"$service_url\">$NAGIOS{SERVICEDESC}</a> on $NAGIOS{HOSTNAME} is in 
    <span style=$style_state>$NAGIOS{SERVICESTATE}</span> state.";
    
    @rows = (
        {
            'title' => 'Notification Type:',
            'data'  => $NAGIOS{NOTIFICATIONTYPE},
        },
        {
            'title' => 'Hostname:',
            'data'  => "<a href=\"$host_url\">$NAGIOS{HOSTNAME}</a>",
        },
        {
            'title' => 'Service Name:',
            'data'  => "<a href=\"$service_url\">$NAGIOS{SERVICEDESC}</a>",
        },
        {
            'title' => 'Service Check Type:',
            'data'  => $NAGIOS{SERVICECHECKTYPE},
        },
        {
            'title' => 'Service Notes:',
            'data'  => $NAGIOS{SERVICENOTES},
        },
    );
} else {

    $notification_title = 'Nagios Host Notification';
    $ack_url = $host_url;
    $output = $NAGIOS{HOSTOUTPUT};
    $summary = "<a href=\"$host_url\">$NAGIOS{HOSTNAME}</a> is in 
    <span style=$style_state>$NAGIOS{HOSTSTATE}</span> state.";

    @rows = (
        {
            'title' => 'Notification Type:',
            'data'  => $NAGIOS{NOTIFICATIONTYPE},
        },
        {
            'title' => 'Hostname:',
            'data'  => "<a href=\"$host_url\">$NAGIOS{HOSTNAME}</a>",
        },
        {
            'title' => 'Notes:',
            'data'  => $NAGIOS{HOSTNOTES},
        },
    );
}

push(@rows,
	{
		'title' => 'IP Address:',
		'data'  => $NAGIOS{HOSTADDRESS},
	},
	{
		'title' => 'Host Alias:',
		'data'  => $NAGIOS{HOSTALIAS},
	},
	{
		'title' => 'Hostgroups:',
		'data'  => $NAGIOS{HOSTGROUPNAMES},
	},
	{
		'title' => 'Event Time:',
		'data'  => $NAGIOS{SHORTDATETIME},
	},
	{
		'title' => 'Location:',
		'data'  => $NAGIOS{LOCATION},
	},
);
        
if($NAGIOS{NOTIFICATIONTYPE} eq 'ACKNOWLEDGEMENT') {
    push(@rows,
        {
            'title' => 'Acknowledged By:',
            'data'  => $NAGIOS{NOTIFICATIONAUTHOR},
        }
    );
    push(@rows,
        {
            'title' => 'Comment:',
            'data'  => $NAGIOS{NOTIFICATIONCOMMENT},
        }
    );
}

# Begin the email

my $body = "<body>
<div style=\"display: block;\"><p>$summary</p>
<p style=\"font-family: monospace; font-size: 12px;\">$output</p><br></div>
<ul><li><a href=\"$nagios_url\">$NAGIOS{LOCATION}</a></li>
<li><a href=\"$NAGIOS{CENTRAL}\">Central Dashboard</a> - all locations</li>";

if ( $NAGIOS{NOTIFICATIONTYPE} == 'PROBLEM' ) {
	$body .= "<li><a href=\"$ack_url\">Acknowledge Alert</a> - acknowledge this</li>";
}

$body .= "</ul><hr><h5>Other information:</h5>
<table border=\"0\" cellpadding=\"4\" cellspacing=\"2\" style=$style_table>";


# Add the rows to the email
for(my $i=0; $i<@rows; $i++) {
    $body .= sprintf('<tr><td style=%s>%s</th><td style=%s>%s</td></tr>',
        $i % 2 == 0 ? $style_th_even : $style_th_odd,
        $rows[$i]->{'title'},
        defined($rows[$i]->{'style'}) ? $rows[$i]->{'style'} : $i % 2 == 0 ? $style_td_even : $style_td_odd,
        $rows[$i]->{'data'}
    );
}
$body .= "</table><br>
<br>
<cite style="font-family: helvetica, arial; font-size: 11px;">This notification is 
automatically sent by Infrastructure Instance of Nagios Monitoring, please reach out to 
<a href="mailto:$NAGIOS{ADMIN}?Subject=Regarding%20Nagios%20Notification">Nagios Admin</a>,
 for any corrections, comments, or concern related to this notification</cite>
</body>";

#NOTIFICATIONRECIPIENTS
if (scalar @skip) {
	$subject = 'Nagios Admin Alert';
}

my $msg = MIME::Lite->new(
    To      => $contact,
    Subject => $subject,
    Type    =>'multipart/related'
);

my $from = $NAGIOS{LOCATION} ? $NAGIOS{LOCATION} . ' <nagios@' . hostname . 'localhost.localdomain>' : '';
if ($from) {
	$msg->add("From" => $from);
}

$msg->attach(Type => 'text/html', Data => $body);
$msg->send();
